@AchieveClubServer_HostAddress = https://localhost:5001


POST {{AchieveClubServer_HostAddress}}/api/users
Content-Type: application/json

{
  RegisrationParams: {
    FirstName : "Test",
                LastName : "Test",
                Email : "test@email.com",
                Avatar : "32234324.png",
                ClubRefId : 1,
                Password : "3453453245345436dfgrefgwef"
  }
}

###
